# Generated by Django 3.1.2 on 2020-11-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_code', models.CharField(max_length=100, unique=True)),
                ('Course_name', models.CharField(max_length=128)),
                ('Dept', models.CharField(max_length=264)),
                ('Units', models.IntegerField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_dept', models.CharField(max_length=264, unique=True)),
                ('Faculty', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_ID', models.CharField(max_length=100, unique=True)),
                ('Staff_first_name', models.CharField(max_length=264)),
                ('Staff_last_name', models.CharField(max_length=264)),
                ('Qualification', models.CharField(max_length=264)),
                ('Dept', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('student_ID', models.IntegerField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('Dept', models.CharField(max_length=264)),
                ('Age', models.IntegerField(max_length=2)),
            ],
        ),
    ]
