# Generated by Django 3.1.2 on 2020-11-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Dept',
        ),
    ]
